name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Download tools
      run: |
        sudo apt-get install -qy libnss3-tools

        mkdir -p $GITHUB_WORKSPACE/bin
        wget -O $GITHUB_WORKSPACE/bin/mkcert "https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64"
        chmod +x $GITHUB_WORKSPACE/bin/mkcert
        echo "::add-path::$GITHUB_WORKSPACE/bin"

        ls -lha $GITHUB_WORKSPACE/bin
    - name: Get and run infra
      run: |
        mkcert -version

        make gen-trusted-ssl

        make run
        sleep 5

    - name: Test
      run: make test
